# https://stackoverflow.com/a/38557845
# this should create the .git dir inside your newly created lib folder
# It is then just a matter to set the remote once it is created `git remote add origin <url>`
from datetime import datetime
import subprocess, shlex
from pathlib import Path

def git(command):
    subprocess.call(shlex.split(f'git {command}'))

git_repo = Path.cwd().joinpath('.git')

if not git_repo.exists():
    git('config --global init.defaultBranch main')
    git('init')
    git('commit --allow-empty -m "Initial commit"')
    git('add -A')
    git(f'commit -m "Generated by michaeljoseph/epitome: {datetime.now():%Y-%m-%d}"')
